// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: third_party/protobuf/json_enumvalue_options.proto
// Protobuf C++ Version: 0.20260427.0

#ifndef third_5fparty_2fprotobuf_2fjson_5fenumvalue_5foptions_2eproto_2eproto_2eh
#define third_5fparty_2fprotobuf_2fjson_5fenumvalue_5foptions_2eproto_2eproto_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#ifdef SWIG
#error "Do not SWIG-wrap protobufs."
#endif  // SWIG
// IWYU pragma: private, include "third_party/protobuf/json_enumvalue_options.proto.h"

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 20260427
#warning "Protobuf C++ gencode is built with an incompatible version of"
#warning "Protobuf C++ headers/runtime. See"
#warning "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/string_view_migration.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_RhC8x4d9MFQ

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_RhC8x4d9MFQ {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_RhC8x4d9MFQ;
}  // extern "C"
namespace pb {
namespace enumvalue {
class JsonEnumValueOptions;
struct JsonEnumValueOptionsGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern JsonEnumValueOptionsGlobalsTypeInternal JsonEnumValueOptions_globals_;
extern const ::google::protobuf::internal::ClassDataFull JsonEnumValueOptions_class_data_;
#else
extern const JsonEnumValueOptionsGlobalsTypeInternal JsonEnumValueOptions_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace enumvalue
}  // namespace pb
namespace google {
namespace protobuf {
class EnumValueOptions;
struct EnumValueOptionsGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern EnumValueOptionsGlobalsTypeInternal EnumValueOptions_globals_;
extern const ::google::protobuf::internal::ClassDataFull EnumValueOptions_class_data_;
#else
extern EnumValueOptionsGlobalsTypeInternal EnumValueOptions_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
extern template void* PROTOBUF_NONNULL Arena::DefaultConstruct<::pb::enumvalue::JsonEnumValueOptions>(Arena* PROTOBUF_NULLABLE);
extern template void* PROTOBUF_NONNULL Arena::CopyConstruct<::pb::enumvalue::JsonEnumValueOptions>(Arena* PROTOBUF_NULLABLE, const void* PROTOBUF_NONNULL);
template <>
internal::GeneratedMessageTraitsT<&::pb::enumvalue::JsonEnumValueOptions_globals_
#ifndef PROTOBUF_MESSAGE_GLOBALS
                                  ,
                                  &::pb::enumvalue::JsonEnumValueOptions_class_data_
#endif  // PROTOBUF_MESSAGE_GLOBALS
                                  >
    internal::MessageTraitsImpl::value<::pb::enumvalue::JsonEnumValueOptions>;
extern template void* PROTOBUF_NONNULL Arena::DefaultConstruct<::google::protobuf::EnumValueOptions>(Arena* PROTOBUF_NULLABLE);
extern template void* PROTOBUF_NONNULL Arena::CopyConstruct<::google::protobuf::EnumValueOptions>(Arena* PROTOBUF_NULLABLE, const void* PROTOBUF_NONNULL);
template <>
internal::GeneratedMessageTraitsT<&::google::protobuf::EnumValueOptions_globals_
#ifndef PROTOBUF_MESSAGE_GLOBALS
                                  ,
                                  &::google::protobuf::EnumValueOptions_class_data_
#endif  // PROTOBUF_MESSAGE_GLOBALS
                                  >
    internal::MessageTraitsImpl::value<::google::protobuf::EnumValueOptions>;
}  // namespace protobuf
}  // namespace google

namespace pb {
namespace enumvalue {

// ===================================================================


// -------------------------------------------------------------------

class  JsonEnumValueOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:pb.enumvalue.JsonEnumValueOptions) */ {
 public:
  inline JsonEnumValueOptions() : JsonEnumValueOptions(nullptr) {}
  ~JsonEnumValueOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(JsonEnumValueOptions* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(JsonEnumValueOptions));
  }
#endif

  template <typename = void>
  explicit constexpr JsonEnumValueOptions(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline JsonEnumValueOptions(const JsonEnumValueOptions& from) : JsonEnumValueOptions(nullptr, from) {}
  inline JsonEnumValueOptions(JsonEnumValueOptions&& from) noexcept : JsonEnumValueOptions(nullptr, ::std::move(from)) {}
  inline JsonEnumValueOptions& operator=(const JsonEnumValueOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline JsonEnumValueOptions& operator=(JsonEnumValueOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  static const char* PROTOBUF_NULLABLE InternalVerify(
      const char* PROTOBUF_NONNULL ptr, ::google::protobuf::internal::ParseContext* PROTOBUF_NONNULL ctx);

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JsonEnumValueOptions& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<JsonEnumValueOptions>(&JsonEnumValueOptions_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(JsonEnumValueOptions& a, JsonEnumValueOptions& b) { a.Swap(&b); }
  inline void Swap(JsonEnumValueOptions* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JsonEnumValueOptions* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JsonEnumValueOptions* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<JsonEnumValueOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const JsonEnumValueOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const JsonEnumValueOptions& from) { JsonEnumValueOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(JsonEnumValueOptions* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "pb.enumvalue.JsonEnumValueOptions"; }

  explicit JsonEnumValueOptions(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  JsonEnumValueOptions(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const JsonEnumValueOptions& from);
  JsonEnumValueOptions(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, JsonEnumValueOptions&& from) noexcept
      : JsonEnumValueOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStringFieldNumber = 1,
  };
  // string string = 1;
  [[nodiscard]] bool has_string()
      const;
  void clear_string() ;
  [[nodiscard]] ::absl::string_view string() const;
  template <typename Arg_ = ::std::string&&>
  void set_string(Arg_&& arg);

  private:
  ::absl::string_view _internal_string() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_string(::absl::string_view value);

  public:
  template <typename FieldType, FieldType>
  struct FieldInfoImpl;
  struct MessageInfoImpl;
  // @@protoc_insertion_point(class_scope:pb.enumvalue.JsonEnumValueOptions)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          0, 48,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const JsonEnumValueOptions& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr string_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_RhC8x4d9MFQ;
};

// ===================================================================



inline constexpr int kJsonFieldNumber = 998;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumValueOptions, ::google::protobuf::internal::MessageTypeTraits< ::pb::enumvalue::JsonEnumValueOptions >, 11, false>(json);

// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// JsonEnumValueOptions

// string string = 1;
inline bool JsonEnumValueOptions::has_string() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void JsonEnumValueOptions::clear_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.string_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::absl::string_view JsonEnumValueOptions::string() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:pb.enumvalue.JsonEnumValueOptions.string)
  return _internal_string();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void JsonEnumValueOptions::set_string(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.string_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:pb.enumvalue.JsonEnumValueOptions.string)
}
inline ::absl::string_view JsonEnumValueOptions::_internal_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.string_.Get();
}
inline void JsonEnumValueOptions::_internal_set_string(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.string_.Set(value, GetArena());
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace enumvalue
}  // namespace pb


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // third_5fparty_2fprotobuf_2fjson_5fenumvalue_5foptions_2eproto_2eproto_2eh
